# Source preparation pipeline to be run from mapterhorn/pipelines folder
[no-cd]
default:
    uv run python source_download.py rw
    uv run python source_to_cog.py rw
    uv run python source_bounds.py rw
    uv run python source_polygonize.py rw 32
    uv run python source_create_tarball.py rw