# Source preparation pipeline to be run from mapterhorn/pipelines folder
[no-cd]
default:
    uv run python source_download.py itlombardia
    uv run python source_unzip.py itlombardia
    uv run python source_bounds.py itlombardia
    uv run python source_polygonize.py itlombardia 32
    uv run python source_create_tarball.py itlombardia