# Source preparation pipeline to be run from mapterhorn/pipelines folder
[no-cd]
default:
    # uv run python source_download.py gebco
    uv run python source_unzip.py gebco
    # uv run python source_normalize_filenames.py gebco
    # uv run python source_bounds.py gebco
    # uv run python source_polygonize.py gebco 32
    # uv run python source_create_tarball.py gebco