# Source preparation pipeline to be run from mapterhorn/pipelines folder
[no-cd]
default:
    uv run python source_download.py ittrentino
    uv run python source_to_cog.py ittrentino
    uv run python source_bounds.py ittrentino
    uv run python source_polygonize.py ittrentino 32
    uv run python source_create_tarball.py ittrentino