# Source preparation pipeline to be run from mapterhorn/pipelines folder
[no-cd]
default:
    uv run python source_download.py itpiemonte
    uv run python source_unzip.py itpiemonte
    uv run python source_bounds.py itpiemonte
    uv run python source_polygonize.py itpiemonte 32
    uv run python source_create_tarball.py itpiemonte